### PR TITLE
Handler now checks against prototype instead of object instance

### LINKED ISSUE #26: Handler silently ignores errors when instantiating Command or Event classes
**Describe the bug**

https://github.com/The-SourceCode/Open-SourceBot/blob/ae60b017713c3c0635aca7fd6823bf58520c7754/src/handler/Handler.js#L59-L66

The code above silently ignores errors thrown while trying to instantiate a Command or Event class. The try/catch clause can't determine whether the error is thrown because `CommandOrEvent` is not a class, or because it gets errors while instantiating it.

**To Reproduce**
1. Create a Command class and give one of the options a wrong datatype.
2. When the application starts an error will be thrown and ignored.

**Expected behavior**
There should be an error to show the Command is invalid, and it shouldn't silently ignore them.

### PR DESCRIPTION
**Pull request by SebastiaanYN**
This fixes #26 by checking if `CommandOrEvent.prototype` is an instance of `Command` or `Event` instead of creating an instance.

### CODE REVIEW

File: src/handler/Handler.js [hunk 1]
```diff
@@ -56,24 +56,15 @@ class Handler {
...
+          if (CommandOrEvent.prototype instanceof Command) {
+            const command = new CommandOrEvent(dependencies);
+            command.category = category;
 
-          // Handle the object, throw an error if it does not extend Command or Event
-          if (commandOrEvent instanceof Command) {
-            commandOrEvent.category = category;
+            this.loadCommand(command);
+          } else if (CommandOrEvent.prototype instanceof Event) {
+            const event = new CommandOrEvent(dependencies);
```
Comment (DarkSeraphim) [inline src/handler/Handler.js]: Shouldn't you set the category, so they can be toggled?

Comment (DarkSeraphim) [reply src/handler/Handler.js]: Also, probably best to try-catch instantiation and log errors?

Comment (SebastiaanYN) [reply src/handler/Handler.js]: > Also, probably best to try-catch instantiation and log errors?

The errors you can get from instantiating a Command/Event should only occur if it has an incorrect set of options. So any errors trying to instantiate it should be thrown to stop the application.
